/**
 * Node type definitions for TraceScope
 * Core data structures for trace node representation
 */

/**
 * Supported node types for差异化 rendering
 * Each type corresponds to a different stage in agent execution
 */
export type NodeType =
  | 'user_input'          // User input/question
  | 'assistant_thought'   // Agent reasoning/thinking
  | 'tool_call'           // Tool/API call request
  | 'code_execution'      // Generated code/script
  | 'execution_result'    // Tool/code execution result
  | 'final_output';       // Final response to user

/**
 * Node execution status
 * Represents the lifecycle state of a node
 */
export type NodeStatus = 'streaming' | 'complete' | 'error';

/**
 * Core node data structure
 * Represents a single unit of trace visualization
 */
export interface StreamNode {
  /**
   * Globally unique node identifier
   * Generated by agent, used for node定位
   */
  nodeId: string;

  /**
   * Parent node ID for tree hierarchy
   * null for root nodes, undefined for pending parent resolution
   */
  parentId?: string | null;

  /**
   * Node type for差异化 styling
   * Determines visual appearance and label
   */
  nodeType?: NodeType;

  /**
   * Content chunk for streaming output
   * node_create: initial content
   * node_append: incremental content fragment
   */
  chunk: string;

  /**
   * Current execution status
   * Default: 'streaming'
   */
  status?: NodeStatus;

  /**
   * Agent identifier for multi-agent data isolation
   */
  agentId?: string;

  /**
   * Node creation timestamp (milliseconds)
   */
  createdAt?: number;

  /**
   * Last update timestamp (milliseconds)
   */
  updatedAt?: number;

  /**
   * Custom extension fields
   * Must be prefixed with 'x-' per protocol specification
   */
  [key: `x-${string}`]: unknown;
}

/**
 * Flattened node storage map
 * O(1) lookup by nodeId
 */
export interface NodeMap {
  [nodeId: string]: StreamNode;
}

/**
 * Node creation event payload
 */
export interface NodeCreateEvent {
  type: 'node_create';
  node: StreamNode;
}

/**
 * Node append event payload
 */
export interface NodeAppendEvent {
  type: 'node_append';
  nodeId: string;
  chunk: string;
  status?: NodeStatus;
}

/**
 * Union type for all node events
 */
export type NodeEvent = NodeCreateEvent | NodeAppendEvent;